# Permalinks
permalink:           pretty

# Setup
title:               jsborjesson
tagline:             Yet another dev blog
url:                 https://jsborjesson.github.io/
paginate:            5
baseurl:             "https://jsborjesson.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jimmy Börjesson
  url:               https://github.com/jsborjesson

# Custom vars
github:
  repo:              https://github.com/jsborjesson/jsborjesson.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
